package practice_17;

public class privateModifiers
{
    private String name;

    //class ko varaible lai private declare garnu is best practice.
    // To make these private varaible accessible by outside of this class we define member function.
    // These member fuctions are generated by IDE itself which is known as getter and setter in java.

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }


}
